# -*- coding: utf-8 -*-
"""Семинар0212.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cydc2sxumnL12SrmZWE_Sn3DlyYtXoLc
"""

#задание1
a = int(input())
b = int(input())
c = int(input())
d = int(input())
 
 
def min4(a, b, c, d):
    return min(min(min(a, b), c), d)
 
 
print("Минимум равен", min4(a, b, c, d))

#задание2
print ("Введите число")
n = int(input())
def my_div(n):
    div = 0
    for i in range (2, n):
        if a % i == 0:
            div = i
    if div == 0:
        return(n)
    else:
        return(div)
print("Наибольший делитель этого числа равен", my_div(n))

#задание3
def my_sum(a, b):
    if b == 0:
        return a
    return my_sum(a+1, b-1)
a = int(input())
b = int(input()) 
 
print(my_sum(a, b))

#задание4
def my_power(a,n):
  if n == 0:
     return 1
  if n < 0:
    return 1 / my_power(a, -n)
  if n % 2 == 0:
    return my_power(a, n // 2) * my_power(a, n // 2)
  else:
    return my_power(a, n - 1) * a
a=int(input())
n=int(input())

print(my_power(a,n))

#задание5
array = ['Makar Sidorov 19', 'Maria Kuznetsova 20', 'Reter Petrov 21', 'Ivan Ivanov 23']
array = sorted(array, key = lambda x: int(x[-2]))
answer = array[0]
for i in range(0, len(array) - 1):
  if array[i] < answer:
     answer = array[i]
print(answer)